### ISSUE TITLE
Use environments for features

### ISSUE THREAD

**Issue by michaelengland** [michaelengland/FlipTheSwitch#17]
`features.yml` file should allow multiple environment settings e.g.:

``` yml
default: &DEFAULT
  some_basic_feature: Yes
  some_development_feature: No

development:
  <<: *DEFAULT
  some_development_feature: Yes

beta:
  <<: *DEFAULT
```

and should be set as option in CLI `--environment` with alias `-e`.
