### ISSUE TITLE
Possibility to add description for feature flags

### ISSUE THREAD

**Issue by SlavkoKrucaj** [michaelengland/FlipTheSwitch#20]
Thank you

**Comment by michaelengland** [comment]
Good idea. We can just change the `yml` format to include an optional description and ignore it elsewhere.

WDYT to this:
```yml
development: &DEVELOPMENT
  amazing_feature:
    enabled: true
  blah_feature:
    enabled: true
    description: 'For when things are just too dull and you want to spice them up'

live:
  <<: *DEVELOPMENT
  blah_feature:
    enabled: false
```
?
