### ISSUE TITLE
Adding support for subfeature

### ISSUE THREAD

**Issue by SlavkoKrucaj** [michaelengland/FlipTheSwitch#22]
Do we think it's available to add subfeatures

```yml
feature_a:
  enabled: true
  feature_b:
     enabled: true
  feature_c:
     enabled: true
feature_d:
  enabled: true
```

which would make appropriate if statements in generated code, 

i.e

isFeatureBEnabled === `[[FlipTheSwitch sharedInstance] isFeatureEnabled:@"feature_a"] && [[FlipTheSwitch sharedInstance] isFeatureEnabled:@"feature_b"];`
